/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.okmich.hackerday.client.tool.dashboard;

import static com.okmich.hackerday.client.tool.dashboard.Handler.*;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.Map;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.WindowConstants;

/**
 *
 * @author m.enudi
 */
public class ClientDashboardFrame extends javax.swing.JFrame {

    private ReportItemPanel panelContext;

    /**
     * Creates new form ClientDashboard
     *
     * @param itemPanelMap
     */
    public ClientDashboardFrame(Map<String, ReportItemPanel> itemPanelMap) {

        initComponents();

        getContentPane().add(itemPanelMap.get(TRAJ_DISTANCE_KEY));
        getContentPane().add(itemPanelMap.get(TRAJ_DURATION_KEY));
        getContentPane().add(itemPanelMap.get(USER_PERIOD_KEY));
        getContentPane().add(itemPanelMap.get(USER_TRAJ_KEY));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new JMenuBar();
        jMenu1 = new JMenu();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geolife Trajectories Dashboard");
        setMinimumSize(new Dimension(800, 600));
        getContentPane().setLayout(new GridLayout(2, 2, 10, 10));

        jMenu1.setText("View Details");
        jMenu1.setEnabled(false);
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JMenu jMenu1;
    private JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    /**
     * @param panelContext the panelContext to set
     */
    void setPanelContext(ReportItemPanel reportItemPanel) {
        if (this.panelContext == null || !this.panelContext.equals(reportItemPanel)) {
            if (this.panelContext != null) {
                this.panelContext.onMouseExit();
            }
            this.panelContext = reportItemPanel;
            jMenu1.setEnabled(true);
        } else {
            this.panelContext.onMouseExit();
            this.panelContext = null;
            jMenu1.setEnabled(false);
        }
    }
}
