/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.okmich.hackerday.client.tool.dashboard;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.Arrays;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.WindowConstants;

/**
 *
 * @author m.enudi
 */
public class ClientDashboard extends javax.swing.JFrame {

    private ReportItemPanel panelContext;

    /**
     * Creates new form ClientDashboard
     */
    public ClientDashboard() {
        trajByDistancePanel = new ReportItemPanel("Distribution of trajectories by distance", this,
                new TrajByDistanceHandler(Arrays.asList("< 5km", "5km ~ 20km", "20km ~ 100km", "≥ 100km")));
        trajByDurationPanel = new ReportItemPanel("Distribution of trajectories by effective duration", this,
                new TrajByDistanceHandler(Arrays.asList("< 1h", "1h ~ 6h", "6h ~ 12h", "≥ 12h")));
        userByPeriodPanel = new ReportItemPanel("Distribution of users by data collection period", this,
                new UserByPeriodHandler(Arrays.asList("< 1week", "1week ~ 1month", "1month ~ 1year", "≥1year")));
        userByTrajPanel = new ReportItemPanel("Distribution of users by trajectories", this,
                new TrajByDistanceHandler(Arrays.asList("< 10", "10 ~ 50", "50 ~ 100", "≥ 100")));

        initComponents();

        getContentPane().add(trajByDistancePanel);
        getContentPane().add(trajByDurationPanel);
        getContentPane().add(userByPeriodPanel);
        getContentPane().add(userByTrajPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new JMenuBar();
        jMenu1 = new JMenu();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geolife Trajectories Dashboard");
        setMinimumSize(new Dimension(800, 600));
        getContentPane().setLayout(new GridLayout(2, 2, 10, 10));

        jMenu1.setText("View Details");
        jMenu1.setEnabled(false);
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ClientDashboard().setVisible(true);
        });
    }

    private final ReportItemPanel trajByDistancePanel;
    private final ReportItemPanel trajByDurationPanel;
    private final ReportItemPanel userByPeriodPanel;
    private final ReportItemPanel userByTrajPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JMenu jMenu1;
    private JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    /**
     * @param panelContext the panelContext to set
     */
    void setPanelContext(ReportItemPanel reportItemPanel) {
        if (this.panelContext == null || !this.panelContext.equals(reportItemPanel)) {
            if (this.panelContext != null) {
                this.panelContext.onMouseExit();
            }
            this.panelContext = reportItemPanel;
            jMenu1.setEnabled(true);
        } else {
            this.panelContext.onMouseExit();
            this.panelContext = null;
            jMenu1.setEnabled(false);
        }
    }
}
